### ISSUE TITLE
Only evaluating `.orJust()` return value when necessary

### ISSUE THREAD

**Issue by benadamstyles** [alexanderjarvis/maybe#13]
Sorry, me again!

I quite often find myself in something like the following situation:

```js
return maybe(props.boolean)
  .filter(bool => bool)
  .map(() =>
    <ComponentIfTrue />
  )
  .orJust(
    <ComponentIfFalse />
  )
```

The trouble is, as I understand it, `<ComponentIfFalse />` will always be evaluated, regardless of the value of `props.boolean`. Would there be the possibility of adding a new method called something like `.orJustCall()` to which you must pass a function, which is only called when the conditions lead to `orJust`? If so I'm happy to PR.

**Comment by alexanderjarvis** [comment]
Hi @Leeds-eBooks,

In this example I would just write a ternary expression. But if you wanted you could pass your own closure (function) to `orJust()` and `map()` to make the entire result lazy. Then you just call it with `()` on the last line.

```
return maybe(props.boolean)
  .filter(bool => bool)
  .map(() =>
    () => <ComponentIfTrue />
  )
  .orJust(
    () => <ComponentIfFalse />
  )()
```

**Comment by benadamstyles** [comment]
Hey @alexanderjarvis, 6 months later I still find myself needing this and while I have used your solution a few times, it feels really verbose when all it needs is another method like `orJust` that accepts a function instead of a value. If I submit a PR, is there any chance of it being accepted?

**Comment by alexanderjarvis** [comment]
Hi @Leeds-eBooks, I actually faced a similar problem yesterday but solved it a different way. I started by looking at `branch` from `recompose` but ended up writing my own HOC instead.

```
import * as React from 'react'

export function intercept<A: {}>(
  condition: (props: A) => boolean,
  Obstruction: React.ComponentType<A>,
): (React.ComponentType<A>) => React.ComponentType<A> {
  return Component => props => {
    if (condition(props)) {
      return <Obstruction {...props} />
    } else {
      return <Component {...props} />
    }
  }
}
```

This lets you specify a component to display if the condition is true, and if not, it falls through the chain to the original component that it wraps. You can use it with `compose` and/or `connect` from redux.

**Comment by benadamstyles** [comment]
Thanks for this, it's really useful (maybe you should suggest it to the `recompose` team!) but actually my question has nothing specifically to do with React. Although my original post referred to a React-based use case, it's really common, at least in the code that I write, that I need to do something expensive if a value is null or undefined, and I don't always want to do that work if the value *is* defined. I'm sensing some resistance 🙂 so I think I will fork, add my changes, submit the PR and then I can use my fork if you don't think it's right for this lib.
