### ISSUE TITLE
Update `maybe` to take a predicate and a value

### ISSUE THREAD

**Issue by evilsoft** [alexanderjarvis/maybe#4]
Would it make sense to update `maybe` to take a predicate function instead of just checking for Nil? This would allow for more flexibility.

something like(in JS):
```js
const maybe = (pred, value) =>
  pred(value) ? just(value) : nothing()
```

That way you let the user decide what Nothing is.

**Comment by alexanderjarvis** [comment]
Hi @evilsoft,

Do you have an example of why you would want to do this? Just so this might help me understand your question further.

I think it would be non-trivial to add a predicate to the existing `maybe` function itself, however it might make sense to instead create a curried version that returns the `maybe` function. For example:

```js
const maybePredicate = (predicate) => (value) => predicate(value) ? just(value) : nothing()
const maybe = maybePredicate(isNil)
...
```

The other concern is the types as it would have to pass the types as generic parameters, which may require rethinking the existing function signatures.

**Comment by evilsoft** [comment]
Maybe imo has very little to do with guarding again just nil values. I see it as a simple way to capture disjunction of any sort. For instance if I need a Number for a specific calculation. If I get a non number I consider it Nothing. The only difference between Maybe and Either is that the Left parameter on Maybe is fixed to unit. So it seems silly to only give the users a lifting function for nil only. Also you could even do some helper that will make any function a Kliseli on Maybe like I did here: https://github.com/evilsoft/crocks/blob/master/README.md#safe-lift

Not a fan of ts and flow. So I do not understand your typing :corn:cerns.

Just a suggestion. Just only guarding for nils seems kinda limiting. Also why not use the fantasyland standard names?

**Comment by alexanderjarvis** [comment]
You're welcome to submit a PR if you'd like to add extra functionality or make aliases for the fantasyland names.

**Comment by alexanderjarvis** [comment]
Also in case you overlooked it, you can use `filter()` as a predicate to consider a non number as a nothing.

**Comment by evilsoft** [comment]
Sorry was traveling. So as an example of how to use the `maybe` with a pred, check out this contrived example here:

[dat-maybe-lesson](https://egghead.io/lessons/javascript-use-a-javascript-array-to-construct-a-maybe)

I did see `filter`, but it seemed odd to have to construct a Just to filter.

I am more curious why you opted to not go with `chain` over `flatMap`. More your reasoning behind that. As a person that makes functional libs, I am always curious the reasoning behind people choices. I guess I am going to have to learn flow, if I am to submit a PR, I do find `of`, `alt`, `traverse` and `ap` super duper helpful, especially for SumTypes like Maybe.

If you respond, go ahead and close this Issue out, and I will make a new one for the alias on flatMap and the addition of alt/applicative/apply/traverse. Although adding the type rep stuff for Alternate and Plus specs would be a MAJOR refactor, so will stay alway from those specs (although they are SOOOO good)

**Comment by alexanderjarvis** [comment]
I decided to go with `flatMap` over `chain` because it's just more familiar to me as I came from using Scala and then Swift. Chain just didn't really make sense.

Adding aliases and missing functions is definitely the next step but I'm going to do so cautiously and only add things as/when they are actually needed.
