### ISSUE TITLE
Unclear purpose

### ISSUE THREAD

**Issue by wellcaffeinated** [alexanderjarvis/maybe#5]
I got here from your medium article. I'm a long time javascript ninja and am a fan of cleanliness and efficiency. I've built a lot of applications, apis, and libraries. But I still don't really see the point.

This isn't a criticism of "maybe" itself (yet). On the contrary, I'm intrigued... (enough to write an issue instead of hitting the back button). I just feel like your examples in the readme are a bit basic and on the surface the only thing I see is that they result in more characters, and inevitably slower execution time than the "problem code". 

And with any optional parameter, at some point you're going to want it to interact with the rest of your logic in a way that is dependant on what the parameter is. So at the end of the day, you're going to write `if ( val.isJust() ){ ... }` instead of `if ( val != null || val !== undefined ){ ... }` or even `if ( !_.isEmpty( val ) ){ ... }`

So... I'm not understanding something. Can you provide more concrete use-cases to demonstrate what problem this solves?

**Comment by alexanderjarvis** [comment]
Hi @wellcaffeinated 

Thanks for taking the time to be intrigued! I understand that it's perhaps not intuitive if you've not used a language with a maybe/option type before. Perhaps if I can try and explain its virtues then you could help me write the Readme to make sense to more people.

The first thing I notice is that your examples all contain `if` statements. On the contrary, part of the motive of using `maybe` would be to avoid using `if` statements (where it makes sense). So in practical terms I don't think I ever really use the `isJust()` function. The real-world use of it is mostly concerned with transforming optional values – so using the `map()` and `flatMap()` functions.

For example:

```js
function isPaginating(state: State): boolean {
  return maybe(state.nextUrl)
    .flatMap(nextUrl => maybe(api.paginate(nextUrl)))
    .map(f => apiIsFetching(f, state))
    .orJust(false)
}
```
instead of
```js
function isPaginating(state: State): boolean {
  const { nextUrl } = state
  if (nextUrl) {
    const f = api.paginate(nextUrl)
    if (f) {
      return apiIsFetching(f)
    }
  }
  return false
}
```

Execution time was never really a primary concern but you raise a valid point. I thought it would be cool to write a babel plugin that transforms the resulting code to make it more performant.

**Comment by wellcaffeinated** [comment]
Thanks for your response.

I understand the basic use-case, when there's one parameter of concern. But what about something like this:

```javascript
function calculatePrice( item: CartItem, coupon: Coupon ): number {
    var price = item.price;

    // if we have a sale price (sale price could be zero)
    if ( item.salePrice !== undefined ){
         if ( item.expiryDate ){
             // only use the sale price if we're not passed the expiry date
             if ( item.expiryDate > Date.now() ){
                 price = item.salePrice;
             }
         } else {
             price = item.salePrice;
         }
    }

    if ( coupon ){
        // discount is decimal "percentage" discount say...
        return price * (1 - coupon.discount);
    }
    
    return price;
}
```

**Comment by alexanderjarvis** [comment]
Then you could do this:

```js
type CartItem = {
  price: number,
  salePrice: ?number,
  expiryDate: ?number,
}

type Coupon = {
  discount: number
}

function calculatePrice(item: CartItem, coupon?: Coupon): number {
  const price = maybe(item.salePrice)
    .flatMap(salePrice =>
      maybe(item.expiryDate).filter(e => e < Date.now()).map(_ => salePrice)
    )
    .orJust(item.price)

  return maybe(coupon).map(c => price * (1 - c.discount))).orJust(price)
}
```

But I would suggest splitting into two functions, one for getting the price and another for applying the coupon.

**Comment by alexanderjarvis** [comment]
Then you could do this:

```js
function calculatePrice(item: CartItem, coupon?: Coupon): number {
  const price = maybe(item.salePrice).map(salePrice =>
      maybe(item.expiryDate)
        .flatMap(e => e > Date.now() ? nothing : just(item.price))
        .orJust(salePrice)
    )
    .orJust(item.price)

  return maybe(coupon).map(c => price * (1 - c.discount)).orJust(price)
}
```

But I would suggest splitting into two functions, one for getting the price and another for applying the coupon.

**Comment by wellcaffeinated** [comment]
Neat. I think more elaborate examples get across the utility better. Still feel like I need to "playtest" this but I understand better.

Also still curious about the performance of it

**Comment by wellcaffeinated** [comment]
Also, it would be great if there were a `dist/` folder with a built and minified version so people have something to use for testing on things like jsperf or jsfiddle or codepen

**Comment by alexanderjarvis** [comment]
I added the `lib/` directory to `.gitignore` because it didn't really make sense to have it in git.

**Comment by ujeenator** [comment]
I think its a little overdo when you can achieve same result with vanilla JS:

```javascript
function calculatePrice( item: CartItem, coupon: Coupon ) : number {
    const {salePrice, expiryDate} = item

    const price = (item.salePrice !== undefined ) 
    ? ( 
        expiryDate 
        ? ( expiryDate > Date.now() ? salePrice : item.price ) 
        : salePrice 
    ) : item.price

    return coupon ? price * (1 - coupon.discount) : price
} 

function isPaginating(state: State): boolean {
    let f

    return state.nextUrl && (f = api.paginate(state.nextUrl)) && apiIsFetching(f) 
}
```

**Comment by webuniverseio** [comment]
@ujeenator it is easier to look at the code with maybe than plain vanilla. [Cyclomatic complexity](http://webuniverse.io/cyclomatic-complexity-refactoring-tips/) is spread out between functions. But I wouldn't use it everywhere.

**Comment by webuniverseio** [comment]
@alexanderjarvis I wonder what are differences with https://github.com/folktale/data.maybe ? Also I find that [Either](https://github.com/folktale/data.either) is easier to use than Maybe because you can define multiple fallback values (Left, vs Nothing). What you think? For example: 
```js
Either
.of(ajaxResponse)
.chain(({status, data}) => status == 200 ? Right(data) : Left('bad status'))
.chain(data => isValid(data) ? Right(parse(data)) : Left('invalid response'))
.fold(handleSuccess, handleError)
```
For async stuff you can obviously use Promises, syntax & logic is pretty much the same.

Also I wonder if you use lodash maybe something like that would do:
```js
_.mixin({maybe: (x, fn) => _.isNil(x) ? x : fn(x)});
_(2).maybe(x => x * 2).maybe(x => x + 2).value() //gives 6
_(null).maybe(x => x * 2).maybe(x => x + 2).value() //give null
```
Note if someone will use this code in production, maybe call it something else than maybe (like perhaps). Reason for that is that lodash might start supporting fantasy land spec & next time you update there will be a conflicting _.maybe...

**Comment by alexanderjarvis** [comment]
@ujeenator I would prefer using Maybe than nested ternary expressions. I agree that the last line where the coupon is applied is very simple though.

Also it would have been much simpler if I could have used `.filter()` when rewriting the function however it didn't handle all the edge cases for this specific example and had to use `.flatMap()` instead.

**Comment by alexanderjarvis** [comment]
@szarouski I would definitely recommend using Either for http responses as it lets you keep more error information. For specific uses though, Maybe is a more natural fit.

The folktale `data.maybe` is very similar but lacks the `flatMap` alias and requires creation using `fromNullable` (which is a bit verbose for my taste). It also doesn't come with flow type lib defs.

**Comment by OliverJAsh** [comment]
I wrote a blog post to argue the reasons for using a Maybe/Option type in JS:

https://oliverjash.me/2017/04/10/why-use-a-maybe-type-in-javascript

In short, it helps avoid coercion and unexpected `null`/`undefined` bugs, and often leads to more concise code.
