### ISSUE TITLE
Consider explaining term "Just" in readme

### ISSUE THREAD

**Issue by jeznag** [alexanderjarvis/maybe#6]
Hi, I've never used a language with Maybe/Monads before and don't understand why a value is "Just" if it's defined. Nothing is intuitive but Just doesn't really make sense to me. I tried googling to find the historical precedent. I can see that it's the same terminology as Haskell but couldn't find an explanation of the etymology.

Could you add something to the README to explain why it's called `just`? Would help me wrap my head around it.

**Comment by benadamstyles** [comment]
This is a guess but I imagine it's to facilitate the nice fluent interface `maybe(value).orJust('default')`.

**Comment by alexanderjarvis** [comment]
Yeah it's just a reference to Haskell.

For example: `Just a` is just a (where a is a value).
