### ISSUE TITLE
forEach

### ISSUE THREAD

**Issue by benadamstyles** [alexanderjarvis/maybe#7]
Firstly, thank you! This has woken me up to a problem I knew I was encountering but couldn't define, and I'm excited to start using it.

Secondly – and this is purely stylistic, and a question rather than an issue – why did you go with `foreach` rather than `forEach`?

**Comment by alexanderjarvis** [comment]
Thanks :) please let me know how it goes as you use it.

Regarding `foreach` – at the time I was probably referencing Scala which is also `foreach`. This isn't necessarily correct and I think it makes sense to change it to be more consistent with Array's `forEach`. This is the same in Swift too and it's generally a more consistent with camelCase conventions.

I'll update in the next version!

**Comment by benadamstyles** [comment]
That's great, thanks – I thought it must be due to the convention in another language, but yeah I think `forEach` makes more sense in JS, not least because my muscle memory really struggles with `foreach`!
